require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.5'

target 'dogstagram' do
  config = use_native_modules!
  # pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'GoogleUtilities', '6.7.1'




  use_react_native!(:path => config["reactNativePath"])

  target 'dogstagramTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'dogstagram-tvOS' do
  # Pods for dogstagram-tvOS

  target 'dogstagram-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
