export const dogBreeds = [
  'Australian Cattle Dog',
  'Australian Shepherd ',
  'Afghan Hound',
  'American English Coonhound',
  'American Foxhound',
  'Azawakh',
  'Bearded Collie',
  'Beauceron',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bergamasco',
  'Berger Picard',
  'Border Collie',
  'Bouvier des Flandres',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Black and Tan Coonhound',
  'Bloodhound',
  'Bluetick Coonhound',
  'Borzoi',
  'Briard',
  'Canaan Dog',
  'Cirneco Dell’ Etna',
  'Cardigan Welsh Corgi',
  'Collie',
  'Entlebucher Mountain Dog',
  'Finnish Lapphund',
  'German Shepherd Dog',
  'Icelandic Sheepdog',
  'Miniature American Shepherd',
  'Norwegian Buhund',
  'Old English Sheepdog',
  'Pembroke Welsh Corgi',
  'Polish Lowland Sheepdog',
  'Puli',
  'Pumi',
  'Pyrenean Shepherd',
  'Shetland Sheepdog',
  'Spanish Water Dog',
  'Swedish Vallhund',
  'Dachshund',
  'English Foxhound',
  'Grand Basset Griffon Vendeen',
  'Greyhound',
  'Harrier',
  'Ibizan Hound',
  'Irish Wolfhound',
  'Norwegian Elkhound',
  'Otterhound',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Plott Hound',
  'Portuguese Podengo Pequeno',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Saluki',
  'Scottish Deerhound',
  'Sloughi',
  'Treeing Walker Coonhound',
  'Whippet',
  'Affenpinscher',
  'Brussels Griffon',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chinese Crested',
  'English Toy Spaniel',
  'Havanese',
  'Italian Greyhound',
  'Japanese Chin',
  'Maltese',
  'Manchester Terrier',
  'Miniature Pinscher',
  'Papillon',
  'Pekingese',
  'Pomeranian',
  'Poodle(Toy)',
  'Pug',
  'Shih Tzu',
  'Silky Terrier',
  'Toy Fox Terrier',
  'Yorkshire Terrier',
  'American Eskimo Dog',
  'Bichon Frise',
  'Boston Terrier',
  'Bulldog',
  'Chinese Shar - Pei',
  'Chow Chow',
  'Coton De Tulear',
  'Dalmatian',
  'Finish Spitz',
  'French Bulldog',
  'Keeshond',
  'Lhasa Apso',
  'Lowchen',
  'Norwegian Lundhund',
  'Poodle',
  'Schipperke',
  'Shiba Inu',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Xoloitzcuintli',
  'American Water Spaniel',
  'Barbet',
  'Boykin Spaniel',
  'Brittany',
  'Chesapeake Bay Retriever',
  'Clumber Spaniel',
  'Cocker Spaniel',
  'Curly - Coated Retriever',
  'English Cocker Spaniel',
  'English Setter',
  'English Springer Spaniel',
  'Field Spaniel',
  'Flat - Coated Retriever',
  'German Shorthaired Pointer',
  'German Wirehaired Pointer',
  'Golden Retriever',
  'Gordon Setter',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Water Spaniel',
  'Labrador Retriever',
  'Lagotto Romagnolo',
  'Nederlandse Kooikerhondje',
  'Nova Scotia Duck Tolling Retriever',
  'Pointer',
  'Spinone Italiano',
  'Sussex Spaniel',
  'Vizsla',
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Airedale Terrier',
  'American Hairless Terrier',
  'American Staffordshire Terrier',
  'Australian Terrier',
  'Bedlington Terrier',
  'Border Terrier',
  'Bull Terrier',
  'Cairn Terrier',
  'Cesky Terrier',
  'Dandie Dinmont Terrier',
  'Glen of Imaal Terrier',
  'Irish Terrier',
  'Kerry Blue Terrier',
  'Lakeland Terrier',
  'Manchester Terrier',
  'Miniature Bull Terrier',
  'Miniature Schnauzer',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Parson Russell Terrier',
  'Rat Terrier',
  'Russell Terrier',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Skye Terrier',
  'Smooth Fox Terrier',
  'Soft Coated Wheaten Terrier',
  'Staffordshire Bull Terrier',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Wire Fox Terrier',
  'Akita',
  'Alaskan Malamute',
  'Anatolian Shepherd Dog',
  'Bernese Mountain Dog',
  'Black Russian Terrier',
  'Boerboel',
  'Boxer',
  'Bullmastiff',
  'Cane Corso',
  'Chinook',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'German Pinscher',
  'Giant Schnauzer',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Komondor',
  'Kuvasz',
  'Leonberger',
  'Mastiff',
  'Neapolitan Mastiff',
  'Newfoundland',
  'Portuguese Water Dog',
  'Rottweiler',
  'Saint Bernard',
  'Samoyed',
  'Siberian Husky',
  'Standard Schnauzer',
  'Tibetan Mastiff',
  'Belgian Laekenois',
  'Biewer Terrier',
  'Bracco Italiano',
  'Dutch Shepherd',
  'Lancashire Heeler',
  'Mudi',
  'Norrbottenspets',
  'Peruvian Inca Orchid',
  'Portuguese Podengo',
  'Russian Toy',
  'Teddy Roosevelt Terrier',
  'American Bulldog',
  'American Leopard Hound',
  'Appenzeller Sennenhund',
  'Australian Kelpie',
  'Australian Stumpy Tail Cattle Dog',
  'Basset Fauve de Bretagne',
  'Bavarian Mountain Scent Hound',
  'Bohemian Shepherd',
  'Bolognese',
  'Braque de Bourbonnais',
  'Braque Francais Pyrenean',
  'Broholmer',
  'Carolina Dog',
  'Catahoula Leopard Dog',
  'Caucasian Shepherd Dog',
  'Central Asian Shepherd Dog',
  'Croatian Sheepdog',
  'Czechoslovakian Vlack',
  'Danish - Swedish Farmdog',
  'Deutscher Wachtelhund',
  'Drentsche Patrijshond',
  'Drever',
  'Estrela Mountain Dog',
  'Eurasier',
  'French Spaniel',
  'German Longhaired Pointer',
  'German Spitz',
  'Hamiltonstovare',
  'Hanoverian Scenthound',
  'Hokkaido',
  'Hovawart',
  'Jagdterrier',
  'Jindo',
  'Kai Ken',
  'Karelian Bear Dog',
  'Kishu Ken',
  'Kromfohrlander',
  'Lapponian Herder',
  'Mountain Cur',
  'Perro de Presa Canario',
  'Porcelaine',
  'Portuguese Pointer',
  'Portuguese Sheepdog',
  'Pudelpointer',
  'Pyrenean Mastiff',
  'Rafeiro de Alentejo',
  'Romanian Mioritic Shepherd Dog',
  'Russian Tsvetnaya Bolonka',
  'Schapendoes',
  'Segugio Italiano',
  'Shikoku',
  'Slovakian Wirehaired Pointer',
  'Slovensky Cuvac',
  'Slovensky Kopov ',
  'Small Musterlander Pointer',
  'Spanish Mastiff',
  'Stabyhoun',
  'Swedish Lapphund',
  'Taiwan Dog',
  'Thai Ridgeback',
  'Tornjak',
  'Tosa',
  'Transylvanian Hound',
  'Treeing Tennessee Brindle',
  'Wetterhoun',
  'Working Kelpie',
  'Yakutian Laika',
];
